name: å‘å¸ƒæ–°ç‰ˆæœ¬
run-name: ${{ github.actor }} æäº¤äº†ä¸€ä¸ªæ–°çš„èŠ‚ç‚¹ç‰ˆæœ¬ ğŸš€

permissions:
  contents: read

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[checkpoint] ') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: å®‰è£…pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 'latest'

      - name: å®‰è£…Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: å®‰è£…ä¾èµ–
        run: |
          pnpm install
          pnpm store prune --force

  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[checkpoint] ') || github.event_name == 'workflow_dispatch'
    needs: cache
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 4

      - name: å®‰è£…pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 'latest'

      - name: å®‰è£…Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: å®‰è£…ä¾èµ–
        run: |
          git clean -ffdx
          pnpm install
          pnpm store prune --force

      - name: æ‰§è¡Œæ„å»º
        run: |
          npm config --location=user set cache="${RUNNER_TEMP}/npm"
          pnpm run build

      - name: æ£€æµ‹ä¿®æ”¹å¹¶æäº¤
        run: source .github/scripts/check-commit.sh

      - name: å‘å¸ƒæ–°ç‰ˆæœ¬
        run: source .github/scripts/publish-all.sh
