name: å‘å¸ƒæ–°ç‰ˆæœ¬
run-name: ${{ github.actor }} æäº¤äº†ä¸€ä¸ªæ–°çš„èŠ‚ç‚¹ç‰ˆæœ¬ ğŸš€

permissions:
  id-token: write
  contents: write

on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      skip_check:
        description: è·³è¿‡â€œæ£€æµ‹ä¿®æ”¹å¹¶æäº¤â€æ­¥éª¤
        required: false
        type: boolean
        default: false

jobs:
  cache:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[checkpoint] ') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v6
        with:
          clean: true

      - name: å®‰è£…pnpm
        uses: pnpm/action-setup@master
        with:
          standalone: true
          cache: true
          package_json_file: package.yaml

      - name: å®‰è£…ä¾èµ–
        run: |
          bash .github/scripts/post-pnpm-install.sh

          pnpm install --frozen-lockfile
          pnpm store prune --force

  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[checkpoint] ') || github.event_name == 'workflow_dispatch'
    needs: cache
    # env:
    #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v6

      - name: å®‰è£…pnpm
        uses: pnpm/action-setup@master
        with:
          standalone: true
          cache: true
          package_json_file: package.yaml

      - name: å®‰è£…ä¾èµ–
        run: |
          bash .github/scripts/post-pnpm-install.sh

          pnpm install --frozen-lockfile
          pnpm store prune --force

      - name: æ‰§è¡Œæ„å»º
        run: |
          npm config --location=user set cache="${RUNNER_TEMP}/npm"
          pnpm run build

      - name: æ£€æµ‹ä¿®æ”¹å¹¶æäº¤
        # if: "!inputs.skip_check"
        run: source .github/scripts/check-commit.sh

      # - name: è·³è¿‡æ£€æµ‹æ‰“åŒ…
      #   if: "inputs.skip_check"
      #   run: pnpm run ???

      - name: å‘å¸ƒæ–°ç‰ˆæœ¬
        run: source .github/scripts/publish-all-tarball.sh
